---
kafka-connect-manager:
  image:
    repository: lsstsqre/kafkaconnect
    tag: 0.8.0
    pullPolicy: Always

  influxdbSink:
    enabled: true
    name: influxdb-sink
    connectInfluxUrl: "http://influxdb.influxdb:8086"
    connectInfluxDb: "example"
    topicRegex: "lsst.sal.*"
    tasksMax: 1
    timestamp: private_sndStamp
    influxSecret: influxdb-auth

## Environment where the EFD is deployed
env: sandbox
