---
kafka-connect-manager:
  image:
    repository: lsstsqre/kafkaconnect
    tag: 0.9.3
    pullPolicy: Always

  secrets:
    influxdb-auth: true

  influxdbSink:
    influxdb-main:
      name: influxdb-main
      enabled: true
      connectInfluxUrl: "http://influxdb.influxdb:8086"
      connectInfluxDb: "efd"
      influxSecret: influxdb-auth
      tasksMax: 1
      topicRegex: "lsst.sal.*logevent_heartbeat"
      autoUpdate: true
      checkInterval: "15000"
      excludedTopicRegex: "lsst.sal.WeatherStation.*"
      timestamp: private_efdStamp
      connectInfluxErrorPolicy: NOOP
      connectInfluxMaxRetries: "10"
      connectInfluxRetryInterval: "60000"
      connectProgressEnabled: false
    influxdb-weather-station:
      name: influxdb-weather-station
      enabled: true
      connectInfluxUrl: "http://influxdb.influxdb:8086"
      connectInfluxDb: "efd"
      influxSecret: influxdb-auth
      tasksMax: 1
      topicRegex: "lsst.sal.WeatherStation.*"
      autoUpdate: true
      checkInterval: "15000"
      excludedTopicRegex: ""
      timestamp: private_efdStamp
      connectInfluxErrorPolicy: NOOP
      connectInfluxMaxRetries: "10"
      connectInfluxRetryInterval: "60000"
      connectProgressEnabled: false

  mirrorMaker2:
    enabled: true
    name: "replicator"
    sourceClusterBootstrapServers: "kafka-0-summit-efd.lsst.codes:31090"
    sourceClusterAlias: ""
    replicationPolicySeparator: ""
    targetClusterBootstrapServers: "lsst-kafka-0-int-efd.ncsa.illinois.edu:31090"
    targetClusterAlias: "int"
    topicRegex: "_schemas,lsst.sal.*logevent_heartbeat,lsst.sal.WeatherStation.*"
    tasksMax: 1
    syncTopicAclsEnabled: false

  s3Sink:
    enabled: true
    name: s3-sink
    s3BucketName: "efd-int"
    s3Region: "us-east-1"
    s3SchemaCompatibility: "NONE"
    s3PartRetries: 3
    s3RetryBackoffMs: 200
    schemaCacheConfig: 5000
    behaviorOnNullValues: "fail"
    topicsDir: "topics"
    awsSecret: "aws-secret"
    flushSize: "1000"
    # invoke file commits to S3 every 10 minutes
    rotateIntervalMs: "600000"
    partitionDurationMs: "3600000"
    pathFormat: "'year'=YYYY/'month'=MM/'day'=dd/'hour'=HH"
    tasksMax: 1
    topicsRegex: "lsst.sal.*"
    checkInterval: "15000"
    excludedTopicRegex: ""
    locale: "en-US"
    timezone: "UTC"
    timestampExtractor: "Record"
    timestampField: ""
    storeUrl: "http://lsst-nfs.ncsa.illinois.edu:9003"


## Environment where the EFD is deployed
env: ncsa-int
