---
kafka-connect-manager:
  image:
    repository: lsstsqre/kafkaconnect
    tag: 0.8.1
    pullPolicy: Always

  influxdbSink:
    enabled: true
    name: influxdb-sink
    connectInfluxUrl: "http://influxdb-0.influxdb.influxdb.svc.cluster.local:8086"
    connectInfluxDb: "efd"
    connectInfluxErrorPolicy: NOOP
    topicRegex: "lsst.sal.*"
    tasksMax: 1
    timestamp: private_sndStamp
    influxSecret: influxdb-auth


## Environment where the EFD is deployed
env: base
