---
kafka-connect-manager:
  image:
    repository: lsstsqre/kafkaconnect
    tag: master
    pullPolicy: Always

  influxdbSink:
    enabled: true
    name: influxdb-sink
    connectInfluxUrl: "http://influxdb.influxdb:8086"
    connectInfluxDb: "efd"
    connectInfluxErrorPolicy: NOOP
    topicRegex: "lsst.sal.*"
    tasksMax: 10
    timestamp: private_sndStamp
    influxSecret: influxdb-auth

## Environment where the EFD is deployed
env: ncsa-stable
