---
kafka-connect-manager:
  image:
    repository: lsstsqre/kafkaconnect
    tag: 0.9.1
    pullPolicy: Always

  secrets:
    influxdb-auth: true

  influxdbSink:
    influxdb-main:
      name: influxdb-main
      enabled: true
      connectInfluxUrl: "http://influxdb.influxdb:8086"
      connectInfluxDb: "efd"
      influxSecret: influxdb-auth
      tasksMax: 10
      topicRegex: "lsst.sal.*"
      autoUpdate: true
      checkInterval: "15000"
      excludedTopicRegex: "lsst.sal.MTM2.*"
      timestamp: private_efdStamp
      connectInfluxErrorPolicy: NOOP
      connectInfluxMaxRetries: "10"
      connectInfluxRetryInterval: "60000"
      connectProgressEnabled: false
    influxdb-atarchiver:
      name: influxdb-mtm2
      enabled: true
      connectInfluxUrl: "http://influxdb.influxdb:8086"
      connectInfluxDb: "efd"
      influxSecret: influxdb-auth
      tasksMax: 10
      topicRegex: "lsst.sal.MTM2.*"
      autoUpdate: true
      checkInterval: "15000"
      timestamp: private_efdStamp
      connectInfluxErrorPolicy: NOOP
      connectInfluxMaxRetries: "10"
      connectInfluxRetryInterval: "60000"
      connectProgressEnabled: false

  mirrorMaker2:
    enabled: true
    name: "replicator"
    sourceClusterBootstrapServers: "kafka-0-summit-efd.lsst.codes:31090"
    sourceClusterAlias: ""
    replicationPolicySeparator: ""
    targetClusterBootstrapServers: "lsst-kafka-0-efd.ncsa.illinois.edu:31090"
    targetClusterAlias: "stable"
    topicRegex: "_schemas,lsst.sal.*"
    tasksMax: 10
    syncTopicAclsEnabled: false


## Environment where the EFD is deployed
env: ncsa-stable
