---
kafka-connect-manager:
  image:
    repository: lsstsqre/kafkaconnect
    tag: 0.9.1
    pullPolicy: Always

  secrets:
    influxdb-auth: true

  influxdbSink:
    influxdb-sink:
      name: influxdb-sink
      enabled: true
      connectInfluxUrl: "http://influxdb.influxdb:8086"
      connectInfluxDb: "efd"
      influxSecret: influxdb-auth
      tasksMax: 1
      topicRegex: "lsst.sal.*"
      autoUpdate: true
      checkInterval: "15000"
      timestamp: private_efdStamp
      connectInfluxErrorPolicy: NOOP
      connectInfluxMaxRetries: "10"
      connectInfluxRetryInterval: "60000"
      connectProgressEnabled: false

## Environment where the EFD is deployed
env: summit
