---
kafka-connect-manager:
  image:
    repository: lsstsqre/kafkaconnect
    tag: tickets-DM-30456
    pullPolicy: Always

  secrets:
    influxdb-auth: true

  influxdbSink:
    influxdb-main:
      name: influxdb-main
      enabled: true
      connectInfluxUrl: "http://influxdb.influxdb:8086"
      connectInfluxDb: "efd"
      influxSecret: influxdb-auth
      tasksMax: 1
      topicRegex: "lsst.sal.*logevent_heartbeat"
      autoUpdate: true
      checkInterval: "15000"
      excludedTopicRegex: "lsst.sal.WeatherStation.*"
      timestamp: private_sndStamp
      connectInfluxErrorPolicy: NOOP
      connectInfluxMaxRetries: "10"
      connectInfluxRetryInterval: "60000"
      connectProgressEnabled: false
    influxdb-weather-station:
      name: influxdb-weather-station
      enabled: true
      connectInfluxUrl: "http://influxdb.influxdb:8086"
      connectInfluxDb: "efd"
      influxSecret: influxdb-auth
      tasksMax: 1
      topicRegex: "lsst.sal.WeatherStation.*"
      autoUpdate: true
      checkInterval: "15000"
      excludedTopicRegex: ""
      timestamp: private_sndStamp
      connectInfluxErrorPolicy: NOOP
      connectInfluxMaxRetries: "10"
      connectInfluxRetryInterval: "60000"
      connectProgressEnabled: false

  mirrorMaker2:
    enabled: true
    name: "replicator"
    sourceClusterBootstrapServers: "kafka-0-summit-efd.lsst.codes:31090"
    sourceClusterAlias: ""
    replicationPolicySeparator: ""
    targetClusterBootstrapServers: "lsst-kafka-0-int-efd.ncsa.illinois.edu:31090"
    targetClusterAlias: "int"
    topicRegex: "_schemas,lsst.sal.*logevent_heartbeat,lsst.sal.WeatherStation.*"
    tasksMax: 1
    syncTopicAclsEnabled: false


## Environment where the EFD is deployed
env: ncsa-int
