chronograf:
  ## Image Settings
  ##
  image:
    repository: "docker.io/chronograf"
    tag: "1.7.14"
    pullPolicy: "Always"

  ## Specify a service type
  ## ClusterIP is default
  ## ref: http://kubernetes.io/docs/user-guide/services/
  ##
  service:
    replicas: 1
    type: ClusterIP

  ## Persist data to a persistent volume
  ##
  persistence:
    enabled: true
    ## chronograf data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: "local-path"
    accessMode: ReadWriteOnce
    size: 8Gi

  ## Configure the ingress object to hook into existing infastructure
  ## ref : http://kubernetes.io/docs/user-guide/ingress/
  ## OPTIONALLY you can set .Values.ingress.secretName to set which secret to use
  ##
  ingress:
    enabled: true
    tls: true
    secretName: tls
    hostname: chronograf-tuscon-teststand-efd.lsst.codes
    annotations:
      kubernetes.io/ingress.class: "nginx"
      # kubernetes.io/tls-acme: "true"

  ## OAuth Settings for OAuth Providers
  ## More information -> https://github.com/influxdata/chronograf/blob/master/docs/auth.md
  ##
  oauth:
    # Need to set to true to use any of the oauth options
    enabled: false
    # Used for JWT to support running multiple copies of Chronograf
    token_secret: CHANGE_ME
    github:
      enabled: false
      client_id: CHANGE_ME
      client_secret: CHANGE_ME
      # This is a comma separated list of GH organizations (OPTIONAL)
      gh_orgs: CHANGE_ME
