oauth2-proxy:
  config:
    existingSecret: control-center-oauth
    configFile: |-
      email_domains = [ "*" ]
      upstreams = [ "http://cp-helm-charts-cp-control-center.cp-helm-charts:9021" ]
      provider = "github"
      github_org = "lsst-sqre"
  image:
    repository: "quay.io/pusher/oauth2_proxy"
    tag: "v4.0.0"
    pullPolicy: "Always"
  service:
    type: ClusterIP
    port: 9021
  ingress:
    enabled: true
    path: /
    hosts:
      - lsst-control-center-nts-efd.lsst.codes
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/proxy-body-size: "0m"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Path /;
    tls:
      - secretName: lsst-codes-tls
        hosts:
          - lsst-control-center-nts-efd.lsst.codes

## Environment where the EFD is deployed
env: ncsa-teststand
