oauth2-proxy:
  config:
    existingSecret: kafdrop-oauth
    configFile: |-
      email_domains = [ "*" ]
      upstreams = [ "http://kafdrop.kafdrop:9000" ]
      provider = "github"
      github_org = "lsst-sqre"
  service:
    type: NodePort
    port: 9000

  ingress:
    enabled: true
    annotations: {kubernetes.io/ingress.class: "nginx"}
    path: /
    hosts:
      - lsst-kafka-0-nts-efd.ncsa.illinois.edu
    tls:
      - secretName: "tls-certs"
        hosts:
          - lsst-kafka-0-nts-efd.ncsa.illinois.edu

## Environment where the EFD is deployed
env: ncsa-teststand
