apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: cp-schema-registry
    app.kubernetes.io/instance: cp-helm-charts
    chart: cp-schema-registry-0.1.0
    heritage: Tiller
    release: cp-helm-charts
  name: cp-helm-charts-cp-schema-registry-jmx
  namespace: cp-helm-charts
spec:
  ports:
  - name: kafka-schema-registry-jmx
    port: 5556
    protocol: TCP
    targetPort: 5556
  selector:
    app: cp-schema-registry
    release: cp-helm-charts
  sessionAffinity: None
  type: ClusterIP
