apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: telegraf-secret
  namespace: telegraf
spec:
  {{- if eq .Values.env "ncsa-int" }}
  path: secret/k8s_operator/lsst-lsp-int.ncsa.illinois.edu/efd/telegraf-secret
  {{- else if eq .Values.env "ncsa-stable" }}
  path: secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/efd/telegraf-secret
  {{- else if eq .Values.env "base" }}
  path: secret/k8s_operator/base-lsp.lsst.codes/efd/telegraf-secret
  {{- else if eq .Values.env "tucson-teststand" }}
  path: secret/k8s_operator/tucson-teststand.lsst.codes/efd/telegraf-secret
  {{- else if eq .Values.env "summit" }}
  path: secret/k8s_operator/summit-lsp.lsst.codes/efd/telegraf-secret
  {{- end }}
  type: Opaque
