apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: tls-certs
  namespace: influxdb
spec:
  {{- if eq .Values.env "ncsa-int" }}
  path: secret/k8s_operator/lsst-lsp-int.ncsa.illinois.edu/efd/tls-certs
  {{- else -}}
  path: secret/dm/square/efd/{{ .Values.env }}/tls-certs
  {{- end }}
  type: Opaque
