---
influxdb:
  ## influxdb image version
  ## ref: https://hub.docker.com/r/library/influxdb/tags/
  image:
    repo: "influxdb"
    tag: "1.8.5"
    pullPolicy: IfNotPresent

  ## Specify a service type
  ## NodePort is default
  ## ref: http://kubernetes.io/docs/user-guide/services/
  ##
  service:
    ## Add annotations to service
    # annotations: {}
    type: ClusterIP
    ## Add IP Cluster
    # clusterIP: ""
    ## Add external IPs that route to one or more cluster nodes
    # externalIPs: []
    ## Specify LoadBalancer IP (only allow on some cloud provider)
    # loadBalancerIP: ""
    ## Allow source IPs to access on service (if empty, any access allow)
    # loadBalancerSourceRanges: []

  ## Persist data to a persistent volume
  ##
  persistence:
    enabled: true
    ## If true will use an existing PVC instead of creating one
    # useExisting: false
    ## Name of existing PVC to be used in the influx deployment
    # name:
    ## influxdb data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: rook-ceph-block
    accessMode: ReadWriteOnce
    size: 1000Gi

  ## Create default user through Kubernetes job
  ## Defaults indicated below
  ##
  setDefaultUser:
    enabled: true

    ## Image of the container used for job
    ## Default: appropriate/curl:latest
    ##
    image: appropriate/curl:latest

    ## Deadline for job so it does not retry forever.
    ## Default: activeDeadline: 300
    ##
    activeDeadline: 300

    ## Restart policy for job
    ## Default: OnFailure
    restartPolicy: OnFailure

    user:

      ## The user name
      ## Default: "admin"
      username: ""

      ## User password
      ## single quotes must be escaped (\')
      ## Default: (Randomly generated 10 characters of AlphaNum)
      # password:

      ## User privileges
      ## Default: "WITH ALL PRIVILEGES"
      privileges: "WITH ALL PRIVILEGES"

      existingSecret: influxdb-auth

  ingress:
    enabled: true
    tls: true
    secretName: tls-certs
    hostname: influxdb-tucson-teststand-efd.lsst.codes
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/proxy-body-size: "0m"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Path /;

  ## Change InfluxDB configuration parameters below:
  ## ref: https://docs.influxdata.com/influxdb/v1.7/administration/config/
  config:
    data:
      cache_max_memory_size: 0
      wal_fsync_delay: "100ms"
      trace_logging_enabled: true
    http:
      enabled: true
      auth_enabled: true
      max_row_limit: 0
    coordinator:
      write_timeout: "60s"
      max_concurrent_queries: 10
      query_timeout: "900s"
      log_queries_after: "15s"
    continuous_queries:
      enabled: false

  backup:
    enabled: false

  ## Customize livenessProbe and readinessProbe
  ## ref: https://docs.influxdata.com/influxdb/v1.7/tools/api/#ping-http-endpoint
  ##
  livenessProbe:
    initialDelaySeconds: 120


## Environment where the EFD is deployed
env: tucson-teststand
