---
kafdrop:
  replicaCount: 1

  kafka:
    brokerConnect: cp-helm-charts-cp-kafka-headless.cp-helm-charts:9092

  host: localhost

  jvm:
    opts: "-Xms32M -Xmx64M"
  jmx:
    port: 5556

  cmdArgs: "--message.format=AVRO --schemaregistry.connect=https://schema-registry-summit-efd.lsst.codes:30828/"

env: summit
