apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: kafdrop-oauth
  namespace: oauth2-proxy
spec:
  {{- if eq .Values.env "ncsa-teststand" }}
  path: secret/k8s_operator/lsst-nts-k8s.ncsa.illinois.edu/efd/kafdrop-oauth
  {{- else if eq .Values.env "ncsa-int" }}
  path: secret/k8s_operator/lsst-lsp-int.ncsa.illinois.edu/efd/kafdrop-oauth
  {{- else if eq .Values.env "ncsa-stable" }}
  path: secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/efd/kafdrop-oauth
  {{- else if eq .Values.env "base" }}
  path: secret/k8s_operator/base-lsp.lsst.codes/efd/kafdrop-oauth
  {{- else if eq .Values.env "tucson-teststand" }}
  path: secret/k8s_operator/tucson-teststand.lsst.codes/efd/kafdrop-oauth
  {{- else if eq .Values.env "summit" }}
  path: secret/k8s_operator/summit-lsp.lsst.codes/efd/kafdrop-oauth
  {{- end }}
  type: Opaque
