apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: schema-registry-http-ingress
  namespace: cp-helm-charts
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: cp-helm-charts-cp-schema-registry
          servicePort: 8081
    {{if eq .Values.env "ncsa-teststand" -}}
    host: lsst-schema-registry-nts-efd.ncsa.illinois.edu
    {{- else if eq .Values.env "ncsa-int" -}}
    host: lsst-schema-registry-int-efd.ncsa.illinois.edu
    {{- else if eq .Values.env "ncsa-stable" -}}
    host: lsst-schema-registry-efd.ncsa.illinois.edu
    {{- else -}}
    host: schema-registry-{{ .Values.env }}-efd.lsst.codes
    {{- end }}
  tls:
  - hosts:
    {{if eq .Values.env "ncsa-teststand" -}}
    - lsst-schema-registry-nts-efd.ncsa.illinois.edu
    {{- else if eq .Values.env "ncsa-int" -}}
    - lsst-schema-registry-int-efd.ncsa.illinois.edu
    {{- else if eq .Values.env "ncsa-stable" -}}
    - lsst-schema-registry-efd.ncsa.illinois.edu
    {{- else -}}
    - schema-registry-{{ .Values.env }}-efd.lsst.codes
    {{- end }}
    secretName: tls-certs
