{{- if and (ne .Values.env "ncsa-int") (ne .Values.env "ncsa-stable") (ne .Values.env "base") -}}
# Argo CD is already deployed on ncsa-int, ncsa-stable and at the base
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: tls-certs
  namespace: argocd
spec:
  path: secret/dm/square/efd/{{ .Values.env }}/tls-certs
  type: Opaque
{{- end -}}
