apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server-http-ingress
  namespace: argocd
  annotations:
    {{if or (eq .Values.env "ncsa-teststand") (eq .Values.env "sandbox") -}}
    # This configuration avoids the 'too many redirect error' seen in k8s
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- else -}}
    # See https://argoproj.github.io/argo-cd/operator-manual/ingress
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    {{- end}}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: argocd-server
          {{if or (eq .Values.env "ncsa-teststand") (eq .Values.env "sandbox") -}}
          servicePort: https
          {{- else -}}
          servicePort: http
          {{- end}}
    {{if eq .Values.env "ncsa-teststand" -}}
    # The DNS is managed by NCSA breaking our convention for
    # naming the services
    host: lsst-argocd-nts-efd.ncsa.illinois.edu
    {{- else -}}
    host: argocd-{{ .Values.env }}.lsst.codes
    {{- end}}
  tls:
  - hosts:
    {{if eq .Values.env "ncsa-teststand" -}}
    - lsst-argocd-nts-efd.ncsa.illinois.edu
    {{- else -}}
    - argocd-{{ .Values.env }}.lsst.codes
    {{- end}}
    secretName: tls-certs
