{{- if and (ne .Values.env "ncsa-int") (ne .Values.env "ncsa-stable") (ne .Values.env "base") -}}
# Argo CD is already deployed on ncsa-int, ncsa-stable and at the base
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server-http-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # This configuration avoids the 'too many redirect error' seen in k8s
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: argocd-server
          {{if or (eq .Values.env "ncsa-teststand") (eq .Values.env "sandbox") -}}
          servicePort: https
          {{- else -}}
          servicePort: http
          {{- end}}
    {{if eq .Values.env "ncsa-teststand" -}}
    # The DNS is managed by NCSA breaking our convention for
    # naming the services
    host: lsst-argocd-nts-efd.ncsa.illinois.edu
    {{- else -}}
    host: argocd-{{ .Values.env }}.lsst.codes
    {{- end}}
  tls:
  - hosts:
    {{if eq .Values.env "ncsa-teststand" -}}
    - lsst-argocd-nts-efd.ncsa.illinois.edu
    {{- else -}}
    - argocd-{{ .Values.env }}.lsst.codes
    {{- end}}
    secretName: tls-certs
{{- end -}}
