{{- if or (eq .Values.env "summit") (eq .Values.env "sandbox") -}}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: tls-certs
  namespace: argocd
spec:
  path: secret/k8s_operator/summit-lsp.lsst.codes/efd/tls-certs
{{- end -}}
