{{- if ne .Values.env "ncsa-int" -}}
# Argo CD is already deployed on ncsa-int
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: tls-certs
  namespace: argocd
spec:
  path: secret/dm/square/efd/{{ .Values.env }}/tls-certs
  type: Opaque
{{- end -}}
