{{- if or (eq .Values.env "summit") (eq .Values.env "sandbox")}}
# nginx-ingress is already deployed on ncsa-teststand, ncsa-int, ncsa-stable, and at the base
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/ingress-nginx
    repoURL: https://github.com/lsst-sqre/argocd-efd
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  ignoreDifferences:
  - group: ""
    kind: Service
    jsonPointers:
    # The Cluster IP is immutable; so we shouldn't look at differences there.
    # If left out, we see the error message:
    #   kubectl failed exit status 1: The Service
    #   "nginx-ingress-controller-metrics" is invalid: spec.clusterIP: Invalid
    #   value: "": field is immutable
    # Credit: https://gist.github.com/kyohmizu/8ebc9c3dcadad6f22dd0246caad9b951
    - /spec/clusterIP
{{- end -}}
