{{- if (ne .Values.env "ncsa-int") -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-aggregator
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kafka-aggregator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/kafka-aggregator
    repoURL: https://github.com/lsst-sqre/argocd-efd
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-{{ .Values.env }}.yaml
{{- end -}}
