{{- if and (ne .Values.env "ncsa-teststand") (ne .Values.env "ncsa-int") (ne .Values.env "ncsa-stable") -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: oauth2-proxy
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/oauth2-proxy
    repoURL: https://github.com/lsst-sqre/argocd-efd
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-{{ .Values.env }}.yaml
{{- end -}}
