{{- if or (eq .Values.env "summit") (eq .Values.env "sandbox") (eq .Values.env "base") -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vault-secrets-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/vault-secrets-operator
    repoURL: https://github.com/lsst-sqre/argocd-efd
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
{{- end -}}
