apiVersion: v1
kind: Namespace
metadata:
  name: chronograf
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chronograf
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: chronograf
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/chronograf
    repoURL: https://github.com/lsst-sqre/argocd-efd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
