---
kafka-connect-manager:
  image:
    repository: lsstsqre/kafka-connect-manager
    tag: v0.6.0
    pullPolicy: Always

  influxdb:
    enabled: true
    name: influxdb-sink-test-timestamp
    influxdbUrl: "https://influxdb-summit-efd.lsst.codes"
    database: "efd-test-timestamp"
    filter: "lsst.sal.*"
    timestamp: private_sndStamp
    existingSecret: influxdb-auth

## Environment where the EFD is deployed
env: summit
