---
telegraf:
  ## Exposed telegraf configuration
  ## ref: https://docs.influxdata.com/telegraf/v1.13/administration/configuration/
  env:
    - name: TELEGRAF_PASSWORD
      valueFrom:
        secretKeyRef:
          name: telegraf-secret
          key: password
# This pulls HOSTNAME from the node, not the pod.
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName

  config:
    # global_tags:
    #   cluster: "mycluster"
    agent:
      interval: "60s"
      round_interval: true
      metric_batch_size: 1000
      metric_buffer_limit: 10000
      collection_jitter: "0s"
      flush_interval: "10s"
      flush_jitter: "0s"
      precision: ""
      debug: false
      quiet: false
      logfile: ""
      hostname: "$HOSTNAME"
      omit_hostname: false
    processors: {}
    inputs:
      - prometheus:
          urls:
            - "http://cp-helm-charts-cp-kafka-connect-jmx.cp-helm-charts:5556/metrics"
            - "http://cp-helm-charts-cp-schema-registry-jmx.cp-helm-charts:5556/metrics"
          metric_version: 2
    outputs:
      - influxdb:
          urls:
            - "http://influxdb.influxdb:8086"
          database: "telegraf"
          retention_policy: ""
          timeout: "5s"
          username: "telegraf"
          password: "$TELEGRAF_PASSWORD"
          user_agent: "telegraf"
          insecure_skip_verify: false
    monitor_self: false


## Environment where the EFD is deployed
env: ncsa-int
